export const autocompleteDemoData = [
  //{ id: "ac", text: "Ascension Island", image: "/images/flags/ac.svg" },
  { id: "ad", text: "Andorra", image: "/images/flags/ad.svg" },
  { id: "ae", text: "United Arab Emirates", image: "/images/flags/ae.svg" },
  { id: "af", text: "Afghanistan", image: "/images/flags/af.svg" },
  { id: "ag", text: "Antigua & Barbuda", image: "/images/flags/ag.svg" },
  { id: "ai", text: "Anguilla", image: "/images/flags/ai.svg" },
  { id: "al", text: "Albania", image: "/images/flags/al.svg" },
  { id: "am", text: "Armenia", image: "/images/flags/am.svg" },
  { id: "ad", text: "Angola", image: "/images/flags/ad.svg" },
  { id: "aq", text: "Antarctica", image: "/images/flags/aq.svg" },
  { id: "ar", text: "Argentina", image: "/images/flags/ar.svg" },
  { id: "as", text: "American Samoa", image: "/images/flags/as.svg" },
  { id: "at", text: "Austria", image: "/images/flags/at.svg" },
  { id: "au", text: "Australia", image: "/images/flags/au.svg" },
  { id: "aw", text: "Aruba", image: "/images/flags/aw.svg" },
  { id: "ax", text: "Åland Islands", image: "/images/flags/ax.svg" },
  { id: "az", text: "Azerbaijan", image: "/images/flags/az.svg" },
  { id: "ba", text: "Bosnia & Herzegovina", image: "/images/flags/ba.svg" },
  { id: "bb", text: "Barbados", image: "/images/flags/bb.svg" },
  { id: "bd", text: "Bangladesh", image: "/images/flags/bd.svg" },
  { id: "be", text: "Belgium", image: "/images/flags/be.svg" },
  { id: "bf", text: "Burkina Faso", image: "/images/flags/bf.svg" },
  { id: "bg", text: "Bulgaria", image: "/images/flags/bg.svg" },
  { id: "bh", text: "Bahrain", image: "/images/flags/bh.svg" },
  { id: "bi", text: "Burundi", image: "/images/flags/bi.svg" },
  { id: "bj", text: "Benin", image: "/images/flags/bj.svg" },
  { id: "bl", text: "St. Barthélemy", image: "/images/flags/bl.svg" },
  { id: "bm", text: "Bermuda", image: "/images/flags/bm.svg" },
  { id: "bn", text: "Brunei", image: "/images/flags/bn.svg" },
  { id: "bo", text: "Bolivia", image: "/images/flags/bo.svg" },
  { id: "bq", text: "Caribbean Netherlands", image: "/images/flags/bq.svg" },
  { id: "br", text: "Brazil", image: "/images/flags/br.svg" },
  { id: "bs", text: "Bahamas", image: "/images/flags/bs.svg" },
  { id: "bt", text: "Bhutan", image: "/images/flags/bt.svg" },
  { id: "bv", text: "Bouvet Island", image: "/images/flags/bv.svg" },
  { id: "bw", text: "Botswana", image: "/images/flags/bw.svg" },
  { id: "by", text: "Belarus", image: "/images/flags/by.svg" },
  { id: "bz", text: "Belize", image: "/images/flags/bz.svg" },
  { id: "ca", text: "Canada", image: "/images/flags/ca.svg" },
  { id: "cc", text: "Cocos (Keeling) Islands", image: "/images/flags/cc.svg" },
  { id: "cg", text: "Congo - Kinshasa", image: "/images/flags/cg.svg" },
  { id: "cf", text: "Central African Republic", image: "/images/flags/cf.svg" },
  { id: "cd", text: "Congo - Brazzaville", image: "/images/flags/cd.svg" },
  { id: "ch", text: "Switzerland", image: "/images/flags/ch.svg" },
  { id: "ci", text: "Côte d’Ivoire", image: "/images/flags/ci.svg" },
  { id: "ck", text: "Cook Islands", image: "/images/flags/ck.svg" },
  { id: "cl", text: "Chile", image: "/images/flags/cl.svg" },
  { id: "cm", text: "Cameroon", image: "/images/flags/cm.svg" },
  { id: "cn", text: "China", image: "/images/flags/cn.svg" },
  { id: "co", text: "Colombia", image: "/images/flags/co.svg" },
  //{ id: "cp", text: "Clipperton Island", image: "/images/flags/cp.svg" },
  { id: "cr", text: "Costa Rica", image: "/images/flags/cr.svg" },
  { id: "cu", text: "Cuba", image: "/images/flags/cu.svg" },
  { id: "cv", text: "Cape Verde", image: "/images/flags/cv.svg" },
  { id: "cw", text: "Curaçao", image: "/images/flags/cw.svg" },
  { id: "cx", text: "Christmas Island", image: "/images/flags/cx.svg" },
  { id: "cy", text: "Cyprus", image: "/images/flags/cy.svg" },
  { id: "cz", text: "Czechia", image: "/images/flags/cz.svg" },
  { id: "de", text: "Germany", image: "/images/flags/de.svg" },
  //{ id: "dg", text: "Diego Garcia", image: "/images/flags/dg.svg" },
  { id: "dj", text: "Djibouti", image: "/images/flags/dj.svg" },
  { id: "dk", text: "Denmark", image: "/images/flags/dk.svg" },
  { id: "dm", text: "Dominica", image: "/images/flags/dm.svg" },
  { id: "do", text: "Dominican Republic", image: "/images/flags/do.svg" },
  { id: "dz", text: "Algeria", image: "/images/flags/dz.svg" },
  //{ id: "ea", text: "Ceuta & Melilla", image: "/images/flags/ea.svg" },
  { id: "ec", text: "Ecuador", image: "/images/flags/ec.svg" },
  { id: "ee", text: "Estonia", image: "/images/flags/ee.svg" },
  { id: "eg", text: "Egypt", image: "/images/flags/eg.svg" },
  { id: "eh", text: "Western Sahara", image: "/images/flags/eh.svg" },
  { id: "er", text: "Eritrea", image: "/images/flags/er.svg" },
  { id: "es", text: "Spain", image: "/images/flags/es.svg" },
  { id: "et", text: "Ethiopia", image: "/images/flags/et.svg" },
  //{ id: "eu", text: "European Union", image: "/images/flags/eu.svg" },
  { id: "fi", text: "Finland", image: "/images/flags/fi.svg" },
  { id: "fj", text: "Fiji", image: "/images/flags/fj.svg" },
  { id: "fk", text: "Falkland Islands", image: "/images/flags/fk.svg" },
  { id: "fm", text: "Micronesia", image: "/images/flags/fm.svg" },
  { id: "fo", text: "Faroe Islands", image: "/images/flags/fo.svg" },
  { id: "fr", text: "France", image: "/images/flags/fr.svg" },
  { id: "ga", text: "Gabon", image: "/images/flags/ga.svg" },
  { id: "gb", text: "United Kingdom", image: "/images/flags/gb.svg" },
  { id: "gd", text: "Grenada", image: "/images/flags/gd.svg" },
  { id: "ge", text: "Georgia", image: "/images/flags/ge.svg" },
  { id: "gf", text: "French Guiana", image: "/images/flags/gf.svg" },
  { id: "gg", text: "Guernsey", image: "/images/flags/gg.svg" },
  { id: "gh", text: "Ghana", image: "/images/flags/gh.svg" },
  { id: "gi", text: "Gibraltar", image: "/images/flags/gi.svg" },
  { id: "gl", text: "Greenland", image: "/images/flags/gl.svg" },
  { id: "gm", text: "Gambia", image: "/images/flags/gm.svg" },
  { id: "gn", text: "Guinea", image: "/images/flags/gn.svg" },
  { id: "gp", text: "Guadeloupe", image: "/images/flags/gp.svg" },
  { id: "gq", text: "Equatorial Guinea", image: "/images/flags/gq.svg" },
  { id: "gr", text: "Greece", image: "/images/flags/gr.svg" },
  { id: "gs", text: "South Georgia & South', Sandwich Islands", image: "/images/flags/gs.svg" },
  { id: "gt", text: "Guatemala", image: "/images/flags/gt.svg" },
  { id: "gu", text: "Guam", image: "/images/flags/gu.svg" },
  { id: "gw", text: "Guinea-Bissau", image: "/images/flags/gw.svg" },
  { id: "gy", text: "Guyana", image: "/images/flags/gy.svg" },
  { id: "hk", text: "Hong Kong SAR China", image: "/images/flags/hk.svg" },
  { id: "hm", text: "Heard & McDonald Islands", image: "/images/flags/hm.svg" },
  { id: "hn", text: "Honduras", image: "/images/flags/hn.svg" },
  { id: "hr", text: "Croatia", image: "/images/flags/hr.svg" },
  { id: "ht", text: "Haiti", image: "/images/flags/ht.svg" },
  { id: "hu", text: "Hungary", image: "/images/flags/hu.svg" },
  //{ id: "ic", text: "Canary Islands", image: "/images/flags/ic.svg" },
  { id: "id", text: "Indonesia", image: "/images/flags/id.svg" },
  { id: "ie", text: "Ireland", image: "/images/flags/ie.svg" },
  { id: "il", text: "Israel", image: "/images/flags/il.svg" },
  { id: "im", text: "Isle of Man", image: "/images/flags/im.svg" },
  { id: "in", text: "India", image: "/images/flags/in.svg" },
  { id: "io", text: "British Indian Ocean Territory", image: "/images/flags/io.svg" },
  { id: "iq", text: "Iraq", image: "/images/flags/iq.svg" },
  { id: "ir", text: "Iran", image: "/images/flags/ir.svg" },
  { id: "is", text: "Iceland", image: "/images/flags/is.svg" },
  { id: "it", text: "Italy", image: "/images/flags/it.svg" },
  { id: "je", text: "Jersey", image: "/images/flags/je.svg" },
  { id: "jm", text: "Jamaica", image: "/images/flags/jm.svg" },
  { id: "jo", text: "Jordan", image: "/images/flags/jo.svg" },
  { id: "jp", text: "Japan", image: "/images/flags/jp.svg" },
  { id: "ke", text: "Kenya", image: "/images/flags/ke.svg" },
  { id: "kg", text: "Kyrgyzstan", image: "/images/flags/kg.svg" },
  { id: "kh", text: "Cambodia", image: "/images/flags/kh.svg" },
  { id: "ki", text: "Kiribati", image: "/images/flags/ki.svg" },
  { id: "km", text: "Comoros", image: "/images/flags/km.svg" },
  { id: "kn", text: "St. Kitts & Nevis", image: "/images/flags/kn.svg" },
  { id: "kp", text: "North Korea", image: "/images/flags/kp.svg" },
  { id: "kr", text: "South Korea", image: "/images/flags/kr.svg" },
  { id: "kw", text: "Kuwait", image: "/images/flags/kw.svg" },
  { id: "ky", text: "Cayman Islands", image: "/images/flags/ky.svg" },
  { id: "kz", text: "Kazakhstan", image: "/images/flags/kz.svg" },
  { id: "la", text: "Laos", image: "/images/flags/la.svg" },
  { id: "lb", text: "Lebanon", image: "/images/flags/lb.svg" },
  { id: "lc", text: "St. Lucia", image: "/images/flags/lc.svg" },
  { id: "li", text: "Liechtenstein", image: "/images/flags/li.svg" },
  { id: "lk", text: "Sri Lanka", image: "/images/flags/lk.svg" },
  { id: "lr", text: "Liberia", image: "/images/flags/lr.svg" },
  { id: "ls", text: "Lesotho", image: "/images/flags/ls.svg" },
  { id: "lt", text: "Lithuania", image: "/images/flags/lt.svg" },
  { id: "lu", text: "Luxembourg", image: "/images/flags/lu.svg" },
  { id: "lv", text: "Latvia", image: "/images/flags/lv.svg" },
  { id: "ly", text: "Libya", image: "/images/flags/ly.svg" },
  { id: "ma", text: "Morocco", image: "/images/flags/ma.svg" },
  { id: "mc", text: "Monaco", image: "/images/flags/mc.svg" },
  { id: "md", text: "Moldova", image: "/images/flags/md.svg" },
  { id: "me", text: "Montenegro", image: "/images/flags/me.svg" },
  { id: "mf", text: "St. Martin", image: "/images/flags/mf.svg" },
  { id: "mg", text: "Madagascar", image: "/images/flags/mg.svg" },
  { id: "mh", text: "Marshall Islands", image: "/images/flags/mh.svg" },
  { id: "mk", text: "North Macedonia", image: "/images/flags/mk.svg" },
  { id: "ml", text: "Mali", image: "/images/flags/ml.svg" },
  { id: "mm", text: "Myanmar (Burma)", image: "/images/flags/mm.svg" },
  { id: "mn", text: "Mongolia", image: "/images/flags/mn.svg" },
  { id: "mo", text: "Macao Sar China", image: "/images/flags/mo.svg" },
  { id: "mp", text: "Northern Mariana Islands", image: "/images/flags/mp.svg" },
  { id: "mq", text: "Martinique", image: "/images/flags/mq.svg" },
  { id: "mr", text: "Mauritania", image: "/images/flags/mr.svg" },
  { id: "ms", text: "Montserrat", image: "/images/flags/ms.svg" },
  { id: "mt", text: "Malta", image: "/images/flags/mt.svg" },
  { id: "mu", text: "Mauritius", image: "/images/flags/mu.svg" },
  { id: "mv", text: "Maldives", image: "/images/flags/mv.svg" },
  { id: "mw", text: "Malawi", image: "/images/flags/mw.svg" },
  { id: "mx", text: "Mexico", image: "/images/flags/mx.svg" },
  { id: "my", text: "Malaysia", image: "/images/flags/my.svg" },
  { id: "mz", text: "Mozambique", image: "/images/flags/mz.svg" },
  { id: "na", text: "Namibia", image: "/images/flags/na.svg" },
  { id: "nc", text: "New Caledonia", image: "/images/flags/nc.svg" },
  { id: "ne", text: "Niger", image: "/images/flags/ne.svg" },
  { id: "nf", text: "Norfolk Island", image: "/images/flags/nf.svg" },
  { id: "ng", text: "Nigeria", image: "/images/flags/ng.svg" },
  { id: "ni", text: "Nicaragua", image: "/images/flags/ni.svg" },
  { id: "nl", text: "Netherlands", image: "/images/flags/nl.svg" },
  { id: "no", text: "Norway", image: "/images/flags/no.svg" },
  { id: "np", text: "Nepal", image: "/images/flags/np.svg" },
  { id: "nr", text: "Nauru", image: "/images/flags/nr.svg" },
  { id: "nu", text: "Niue", image: "/images/flags/nu.svg" },
  { id: "nz", text: "New Zealand", image: "/images/flags/nz.svg" },
  { id: "om", text: "Oman", image: "/images/flags/om.svg" },
  { id: "pa", text: "Panama", image: "/images/flags/pa.svg" },
  { id: "pe", text: "Peru", image: "/images/flags/pe.svg" },
  { id: "pf", text: "French Polynesia", image: "/images/flags/pf.svg" },
  { id: "pg", text: "Papua New Guinea", image: "/images/flags/pg.svg" },
  { id: "ph", text: "Philippines", image: "/images/flags/ph.svg" },
  { id: "pk", text: "Pakistan", image: "/images/flags/pk.svg" },
  { id: "pl", text: "Poland", image: "/images/flags/pl.svg" },
  { id: "pm", text: "St. Pierre & Miquelon", image: "/images/flags/pm.svg" },
  { id: "pn", text: "Pitcairn Islands", image: "/images/flags/pn.svg" },
  { id: "pr", text: "Puerto Rico", image: "/images/flags/pr.svg" },
  { id: "ps", text: "Palestinian Territories", image: "/images/flags/ps.svg" },
  { id: "pt", text: "Portugal", image: "/images/flags/pt.svg" },
  { id: "pw", text: "Palau", image: "/images/flags/pw.svg" },
  { id: "py", text: "Paraguay", image: "/images/flags/py.svg" },
  { id: "qa", text: "Qatar", image: "/images/flags/qa.svg" },
  { id: "re", text: "Réunion", image: "/images/flags/re.svg" },
  { id: "ro", text: "Romania", image: "/images/flags/ro.svg" },
  { id: "rs", text: "Serbia", image: "/images/flags/rs.svg" },
  { id: "ru", text: "Russia", image: "/images/flags/ru.svg" },
  { id: "rw", text: "Rwanda", image: "/images/flags/rw.svg" },
  { id: "sa", text: "Saudi Arabia", image: "/images/flags/sa.svg" },
  { id: "sb", text: "Solomon Islands", image: "/images/flags/sb.svg" },
  { id: "sc", text: "Seychelles", image: "/images/flags/sc.svg" },
  { id: "sd", text: "Sudan", image: "/images/flags/sd.svg" },
  { id: "se", text: "Sweden", image: "/images/flags/se.svg" },
  { id: "sg", text: "Singapore", image: "/images/flags/sg.svg" },
  { id: "sh", text: "St. Helena", image: "/images/flags/sh.svg" },
  { id: "si", text: "Slovenia", image: "/images/flags/si.svg" },
  { id: "sj", text: "Svalbard & Jan Mayen", image: "/images/flags/sj.svg" },
  { id: "sk", text: "Slovakia", image: "/images/flags/sk.svg" },
  { id: "sl", text: "Sierra Leone", image: "/images/flags/sl.svg" },
  { id: "sm", text: "San Marino", image: "/images/flags/sm.svg" },
  { id: "sn", text: "Senegal", image: "/images/flags/sn.svg" },
  { id: "so", text: "Somalia", image: "/images/flags/so.svg" },
  { id: "sr", text: "Suriname", image: "/images/flags/sr.svg" },
  { id: "ss", text: "South Sudan", image: "/images/flags/ss.svg" },
  { id: "st", text: "São Tomé & Príncipe", image: "/images/flags/st.svg" },
  { id: "sv", text: "El Salvador", image: "/images/flags/sv.svg" },
  { id: "sx", text: "Sint Maarten", image: "/images/flags/sx.svg" },
  { id: "sy", text: "Syria", image: "/images/flags/sy.svg" },
  { id: "sz", text: "Eswatini", image: "/images/flags/sz.svg" },
  { id: "sh", text: "Tristan Da Cunha", image: "/images/flags/sh.svg" },
  { id: "tc", text: "Turks & Caicos Islands", image: "/images/flags/tc.svg" },
  { id: "td", text: "Chad", image: "/images/flags/td.svg" },
  { id: "tf", text: "French Southern Territories", image: "/images/flags/tf.svg" },
  { id: "tg", text: "Togo", image: "/images/flags/tg.svg" },
  { id: "th", text: "Thailand", image: "/images/flags/th.svg" },
  { id: "tj", text: "Tajikistan", image: "/images/flags/tj.svg" },
  { id: "tk", text: "Tokelau", image: "/images/flags/tk.svg" },
  { id: "tl", text: "Timor-Leste", image: "/images/flags/tl.svg" },
  { id: "tm", text: "Turkmenistan", image: "/images/flags/tm.svg" },
  { id: "tn", text: "Tunisia", image: "/images/flags/tn.svg" },
  { id: "to", text: "Tonga", image: "/images/flags/to.svg" },
  { id: "tr", text: "Turkey", image: "/images/flags/tr.svg" },
  { id: "tt", text: "Trinidad & Tobago", image: "/images/flags/tt.svg" },
  { id: "tv", text: "Tuvalu", image: "/images/flags/tv.svg" },
  { id: "tw", text: "Taiwan", image: "/images/flags/tw.svg" },
  { id: "tz", text: "Tanzania", image: "/images/flags/tz.svg" },
  { id: "ua", text: "Ukraine", image: "/images/flags/ua.svg" },
  { id: "ug", text: "Uganda", image: "/images/flags/ug.svg" },
  { id: "um", text: "U.S. Outlying Islands", image: "/images/flags/um.svg" },
  //{ id: "un", text: "United Nations", image: "/images/flags/un.svg" },
  { id: "us", text: "United States", image: "/images/flags/us.svg" },
  { id: "uy", text: "Uruguay", image: "/images/flags/uy.svg" },
  { id: "uz", text: "Uzbekistan", image: "/images/flags/uz.svg" },
  { id: "va", text: "Vatican City", image: "/images/flags/va.svg" },
  { id: "vc", text: "St. Vincent & Grenadines", image: "/images/flags/vc.svg" },
  { id: "ve", text: "Venezuela", image: "/images/flags/ve.svg" },
  { id: "vg", text: "British Virgin Islands", image: "/images/flags/vg.svg" },
  { id: "vi", text: "U.S. Virgin Islands", image: "/images/flags/vi.svg" },
  { id: "vn", text: "Vietnam", image: "/images/flags/vn.svg" },
  { id: "vu", text: "Vanuatu", image: "/images/flags/vu.svg" },
  { id: "wf", text: "Wallis & Futuna", image: "/images/flags/wf.svg" },
  { id: "ws", text: "Samoa", image: "/images/flags/ws.svg" },
  { id: "xk", text: "Kosovo", image: "/images/flags/xk.svg" },
  { id: "ye", text: "Yemen", image: "/images/flags/ye.svg" },
  { id: "yt", text: "Mayotte", image: "/images/flags/yt.svg" },
  { id: "za", text: "South Africa", image: "/images/flags/za.svg" },
  { id: "zm", text: "Zambia", image: "/images/flags/zm.svg" },
  { id: "zw", text: "Zimbabwe", image: "/images/flags/zw.svg" },
  { id: "uk", text: "England", image: "/images/flags/gb-eng.svg" },
  { id: "uk", text: "Scotland", image: "/images/flags/gb-sct.svg" },
  { id: "uk", text: "Wales", image: "/images/flags/gb-wls.svg" },
];
